name: Submit Dependency Graph

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to check out the code and submit a dependency graph snapshot

env:
  JAVA_VERSION: 17

jobs:
  submit-dependency-graph:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@db19848a5fa7950289d3668fb053140cf3028d43 # v3
        env:
          DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ":build-logic"
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: "compileClasspath|runtimeClasspath"
